spring.application.name=user-service

#server config
server.port=8082

#Database config(Mysql)
#jdbc:<database_type>://<host>:<port>/<database_name>
spring.datasource.url=jdbc:mysql://localhost:3306/bug_ai_user
spring.datasource.username=root
spring.datasource.password=root#123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA /Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

#Connection Pool
#pool size , minimum connection available, Close idle after 30s, Wait 20s for connection
spring.datasource.hikari.maximum-pool-size=10 
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000

#Logging
#Spring web =info (logs api calls),logs sql queries,logs query parameter eg email
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#Security
#10 means no of time ByCrypt algo will hash the password so it hashes 2^10 times
security.password.encoder.strength=10


#Acutator gives internal app info
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
